version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: docker-hub.kenbun.de/kenbuntraining/jupyterlab:3.4.3-spark-3.3.0
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
      - 5001:5000
    volumes:
      - shared-workspace:/opt/workspace
  spark-master:
    image: docker-hub.kenbun.de/kenbuntraining/spark-master:3.3.0
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: docker-hub.kenbun.de/kenbuntraining/spark-worker:3.3.0
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2048m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
#  spark-worker-2:
#    image: docker-hub.kenbun.de/kenbuntraining/spark-worker:3.3.0
#    container_name: spark-worker-2
#    environment:
#      - SPARK_WORKER_CORES=2
#      - SPARK_WORKER_MEMORY=512m
#    ports:
#      - 8082:8081
#    volumes:
#      - shared-workspace:/opt/workspace
#    depends_on:
#      - spark-master
#  spark-worker-3:
#    image: docker-hub.kenbun.de/kenbuntraining/spark-worker:3.3.0
#    container_name: spark-worker-3
#    environment:
#      - SPARK_WORKER_CORES=2
#      - SPARK_WORKER_MEMORY=512m
#    ports:
#      - 8083:8081
#    volumes:
#      - shared-workspace:/opt/workspace
#    depends_on:
#      - spark-master
  docker-postgres-world-db:
    image: docker-hub.kenbun.de/kenbuntraining/docker-postgres-world-db:latest
    container_name: docker-postgres-world-db
    ports:
      - 5432:5432
    depends_on:
      - spark-master
  spark-client:
    image: docker-hub.kenbun.de/kenbuntraining/spark-client:3.3.0
    container_name: spark-client
    ports:
      - 8040:4040    
    volumes:
      - shared-workspace:/opt/workspace    
    depends_on:
      - spark-master
  spark-dashboard:
    image: docker-hub.kenbun.de/kenbuntraining/spark-dashboard:latest
    container_name: spark-dashboard
    ports:
      - 2003:2003
      - 8086:8086
      - 3000:3000
    volumes:
      - shared-workspace:/opt/workspace    
    depends_on:
      - spark-master
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1    
...